server:
  port: 8090

spring:
  application:
    name: impressao

  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 1
    consumer:
      group-id: relatorio
      bootstrapServers: ${spring.kafka.bootstrap-servers}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.apache.kafka.common.serialization.StringSerializer
    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false