server:
  port: 8082

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/
#    register-with-eureka: true


# -------------------------- Bruno Leite --------------------------
spring:
  application:
    name: residencial
  jpa:
    show-sql: true
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #  jmx:
  #    enabled: false
  datasource:
    url : jdbc:mysql://localhost:3306/seguros?useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root

axon:
  serializer:
    general: jackson
  eventhandling:
    processors:
      name:
        mode: tracking



#  datasource_consulta:
#    url: jdbc:mysql://localhost:3306/seguros_consulta?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&sslMode=DISABLED
#    username: root
#    password: root

#  mysql_2:
#    datasource:
#        url: jdbc:mysql://localhost:3306/seguros_consulta?useTimezone=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&sslMode=DISABLED
#        username: root
#        password: root

#TODO EnabledJWT
#jwt:
#  config:
#    type: signed