server:
  port: 8082

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/
#    register-with-eureka: true


# -------------------------- Bruno Leite --------------------------
spring:
  flyway:
    baseline-on-migrate: true
  application:
    name: residencial
  jpa:
    show-sql: true
#    hibernate:
#      ddl-auto:  update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  #  jmx:
  #    enabled: false
  datasource:
    url : jdbc:mysql://localhost:3306/seguros?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&sslMode=DISABLED
    #url : jdbc:mysql://db:3306/seguros?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=America/Sao_Paulo&allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      retries: 10
      bootstrap-servers: ${spring.kafka.bootstrap-servers}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    jackson:
      serialization:
        WRITE_DATES_AS_TIMESTAMPS: false

#TODO EnabledJWT
#jwt:
#  config:
#    type: signed